{% set name = "connected-components-3d" %}
{% set version = "3.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/connected-components-3d-{{ version }}.tar.gz
  sha256: a48af38d45e51b86d7f027d82f480768e794ca09904bf167410594cd021e4b1b

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pbr
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cc3d
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/connected-components-3d
  summary: Connected components on 2D and 3D images. Supports multiple labels.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/seung-lab/connected-components-3d/

extra:
  recipe-maintainers:
    - goanpeca
    - william-silversmith
    - stuarteberg
