{% set name = "connected-components-3d" %}
{% set version = "3.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connected-components-3d-{{ version }}.tar.gz
  sha256: c73adda66af4f30dd20dcf15802c0aaf7b841e90f7600f4abaf6b9bf0143f867

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pbr
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cc3d
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seung-lab/connected-components-3d/
  summary: Connected components on 2D and 3D images. Supports multiple labels.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - william-silversmith
